[tool.poetry]
name = "python-core"
version = "0.1.0"
description = "Python core logic for Bluetooth chat application"
authors = ["RamNileshPathak <ramnileshpathak@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
cryptography = "^42.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
